global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/<hook-id>' # enter webhook id

route:
  receiver: 'slack'

receivers:
- name: 'slack'
  slack_configs:
  - channel: '#prometheus'
    send_resolved: true
