version: "3.8"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    privileged: true
    ports:
      - 9090:9090
    volumes:
      - "./prometheus:/etc/prometheus:ro"
      - "prometheus_data:/prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    links:
      - alertmanager:alertmanager
    networks:
      - goprom
    restart: always
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager:/etc/alertmanager/
    networks:
      - goprom
    restart: always
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    user: "472"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - goprom
    restart: always
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter
    ports:
      - 9100:9100
    networks:
      - goprom
  goprom_1:
    container_name: worker1
    image: shekeriev/goprom
    ports:
      - 8081:8080
    networks:
      - goprom
  goprom_2:
    container_name: worker2
    image: shekeriev/goprom
    ports:
      - 8082:8080
    networks:
      - goprom
volumes:
  grafana_data:
    name: grafana_data
    external: false
  prometheus_data:
    name: prometheus_data
    external: false
networks:
  goprom:
