global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - rules.yml
 
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['192.168.34.101:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']
  - job_name: 'goprom'
    static_configs:
    - targets: ['192.168.34.101:8081', '192.168.34.101:8082']
  - job_name: 'docker'
    static_configs:
    - targets: ['192.168.34.101:9323'] 
